name: zainik_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: ^0.13.6
  flutter_staggered_grid_view: ^0.4.0
  shimmer: 3.0.0
  flutter_svg: 2.0.7
  flutter_animate: 4.2.0+1
  d_dialog: 1.0.1
  flutter: 
    sdk: flutter
  loading_animation_widget: ^1.2.0+4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true
fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-Italic.ttf
          style: italic

